name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automated commit for issue : ${{ github.sha }}"
        assignees: |
          ManojCSE17

